spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: sanjeevi
    password: sanju-db
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # or 'update', 'create', 'create-drop' depending on your need
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  # (Optional) Enable SQL logging
  logging:
    level:
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql: TRACE

# (Optional) Server settings
server:
  port: 8085
