openapi: 3.0.3
info:
  title: Order Management API
  description: RESTful API for managing orders in vertical slice architecture
  version: 1.0.0

servers:
  - url: http://localhost:8080
    description: Local development server

paths:
  /orders:
    post:
      summary: Create a new order
      description: Creates a new order in DRAFT status
      operationId: createOrder
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateOrderRequest'
            example:
              customerId: "CUST1234"
              items:
                - productId: "PRD00001"
                  productName: "Wireless Headphones"
                  quantity: 2
                  unitPriceCents: 7999
                - productId: "PRD00002"
                  productName: "USB Cable"
                  quantity: 1
                  unitPriceCents: 1299
      responses:
        '201':
          description: Order created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderResponse'
        '400':
          description: Invalid request data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Customer not found or inactive
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    get:
      summary: List all orders
      description: Retrieve a paginated list of orders with optional filtering
      operationId: listOrders
      parameters:
        - name: customerId
          in: query
          description: Filter by customer ID
          required: false
          schema:
            type: string
            pattern: '^CUST[A-Za-z0-9]{4,8}$'
        - name: status
          in: query
          description: Filter by order status
          required: false
          schema:
            $ref: '#/components/schemas/OrderStatus'
        - name: page
          in: query
          description: Page number (1-based)
          required: false
          schema:
            type: integer
            minimum: 1
            default: 1
        - name: limit
          in: query
          description: Number of items per page
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
      responses:
        '200':
          description: List of orders
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderListResponse'
        '400':
          description: Invalid query parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /orders/{orderId}:
    get:
      summary: Get order details
      description: Retrieve detailed information about a specific order
      operationId: getOrder
      parameters:
        - name: orderId
          in: path
          required: true
          description: Unique identifier for the order
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Order details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderResponse'
        '404':
          description: Order not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    patch:
      summary: Update order status
      description: Update the status of an existing order
      operationId: updateOrderStatus
      parameters:
        - name: orderId
          in: path
          required: true
          description: Unique identifier for the order
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateOrderStatusRequest'
            example:
              status: "CONFIRMED"
      responses:
        '200':
          description: Order status updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderResponse'
        '400':
          description: Invalid status transition
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Order not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    CreateOrderRequest:
      type: object
      required:
        - customerId
        - items
      properties:
        customerId:
          type: string
          pattern: '^CUST[A-Za-z0-9]{4,8}$'
          description: Customer identifier
        items:
          type: array
          minItems: 1
          maxItems: 20
          items:
            $ref: '#/components/schemas/CreateOrderItemRequest'
          description: List of items to include in the order

    CreateOrderItemRequest:
      type: object
      required:
        - productId
        - productName
        - quantity
        - unitPriceCents
      properties:
        productId:
          type: string
          pattern: '^PRD[0-9]{5}$'
        productName:
          type: string
        quantity:
          type: integer
          minimum: 1
        unitPriceCents:
          type: integer
          minimum: 0

    UpdateOrderStatusRequest:
      type: object
      required:
        - status
      properties:
        status:
          $ref: '#/components/schemas/OrderStatus'

    OrderResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
        customerId:
          type: string
          pattern: '^CUST[A-Za-z0-9]{4,8}$'
        status:
          $ref: '#/components/schemas/OrderStatus'
        items:
          type: array
          items:
            $ref: '#/components/schemas/OrderItemResponse'
        subtotalCents:
          type: integer
          format: int64
          minimum: 0
        taxCents:
          type: integer
          format: int64
          minimum: 0
        shippingCents:
          type: integer
          format: int64
          minimum: 0
        totalCents:
          type: integer
          format: int64
          minimum: 100
        createdAt:
          type: string
          format: date-time
        confirmedAt:
          type: string
          format: date-time
          nullable: true
        shippedAt:
          type: string
          format: date-time
          nullable: true
        deliveredAt:
          type: string
          format: date-time
          nullable: true
        cancelledAt:
          type: string
          format: date-time
          nullable: true

    OrderItemResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
        productId:
          type: string
          pattern: '^PRD[0-9]{5}$'
        productName:
          type: string
        quantity:
          type: integer
          minimum: 1
        unitPriceCents:
          type: integer
          minimum: 0

    OrderListResponse:
      type: object
      properties:
        orders:
          type: array
          items:
            $ref: '#/components/schemas/OrderResponse'
        pagination:
          $ref: '#/components/schemas/PaginationResponse'

    PaginationResponse:
      type: object
      properties:
        page:
          type: integer
          minimum: 1
        limit:
          type: integer
          minimum: 1
        totalItems:
          type: integer
          minimum: 0
        totalPages:
          type: integer
          minimum: 0
        hasNext:
          type: boolean
        hasPrevious:
          type: boolean

    OrderStatus:
      type: string
      enum:
        - DRAFT
        - CONFIRMED
        - SHIPPED
        - DELIVERED
        - CANCELLED

    ErrorResponse:
      type: object
      required:
        - error
        - message
      properties:
        error:
          type: string
          example: "INVALID_REQUEST"
        message:
          type: string
          example: "Order must have at least 1 item"
        details:
          type: object
          additionalProperties: true
        timestamp:
          type: string
          format: date-time
